version: "3.5"
networks:
  default:
    name: x1
    
services:
  x1-state-db:
    container_name: x1-state-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./test/config/prover/initproverdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  x1-pool-db:
    container_name: x1-pool-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command: ["postgres", "-N", "500"]

  x1-bridge-db:
    container_name: x1-bridge-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  x1-bridge-redis:
    container_name: x1-bridge-redis
    image: redis
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_PORT=6379
      - REDIS_DATABASES=8

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181

  x1-bridge-coin-kafka:
    image: wurstmeister/kafka
    container_name: x1-bridge-coin-kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9123
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9123
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CREATE_TOPICS: "explorer_chainAddressPrice_push:1:1"

  x1-bridge-service-api:
    container_name: x1-bridge-service-api
    image: x1-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=x1-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./sentinel/config.json:/app/sentinel_config.json
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-bridge runAPI --cfg /app/config.toml"

  x1-bridge-service-task:
    container_name: x1-bridge-service-task
    image: x1-bridge-service
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=x1-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-bridge runTask --cfg /app/config.toml"

  x1-bridge-service-push:
    container_name: x1-bridge-service-push
    image: x1-bridge-service
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=x1-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-bridge runPushTask --cfg /app/config.toml"

  x1-node:
    container_name: x1-node
    image: okexchain/x1-node:origin_release_v0.3.0_20240318080219_e0ef30d4
    ports:
      - 8123:8123
      - 61090:61090
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=x1-state-db
      - ZKEVM_NODE_POOL_HOST=x1-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=x1-rpc-db
      - ZKEVM_NODE_SEQUENCER_FINALIZER_BATCHMAXDELTATIMESTAMP="4s"
      - ZKEVM_NODE_SEQUENCER_FINALIZER_L2BLOCKMAXDELTATIMESTAMP="1s"
    volumes:
      - ./test/test.keystore.sequencer:/pk/keystore.sequencer
      - ./test/test.keystore.aggregator:/pk/keystore.aggregator
      - ./test/config/node/config.zkevm.node.toml:/app/config.toml
      - ./test/config/node/genesis.local.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-node approve --network custom --custom-network-file /app/genesis.json --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml --key-store-path /pk/keystore.sequencer --password testonly &&
         /app/x1-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"synchronizer,rpc,sequencer,sequence-sender,aggregator,eth-tx-manager,l2gaspricer\" --http.api eth,net,debug,zkevm,txpool,web3"

  x1-node-v1tov2:
    container_name: x1-node-v1tov2
    image: okexchain/x1-node:origin_release_v0.3.0_20240318080219_e0ef30d4
    ports:
      - 8123:8123
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=x1-state-db
      - ZKEVM_NODE_POOL_HOST=x1-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=x1-rpc-db
      - ZKEVM_NODE_ETHERMAN_URL=http://x1-v1tov2-l1-network:8545
      - ZKEVM_NODE_EXECUTOR_URI=x1-prover-v1tov2:50071
      - ZKEVM_NODE_MTCLIENT_URI=x1-prover-v1tov2:50061
    volumes:
      - ./test/test.keystore.sequencer:/pk/keystore.sequencer
      - ./test/test.keystore.aggregator:/pk/keystore.aggregator
      - ./test/config/node/config.zkevm.node.toml:/app/config.toml
      - ./test/config/node/genesis.local-v1tov2.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-node approve --network custom --custom-network-file /app/genesis.json --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml --key-store-path /pk/keystore.sequencer --password testonly &&
         /app/x1-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"synchronizer,rpc,sequencer,sequence-sender,eth-tx-manager,l2gaspricer\" --http.api eth,net,debug,zkevm,txpool,web3"

  x1-aggregator-v1tov2:
    container_name: x1-aggregator-v1tov2
    image: okexchain/x1-node:origin_release_v0.3.0_20240318080219_e0ef30d4
    ports:
      - 9092:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=x1-state-db
      - ZKEVM_NODE_POOL_HOST=x1-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=x1-rpc-db
      - ZKEVM_NODE_ETHERMAN_URL=http://x1-v1tov2-l1-network:8545
      - ZKEVM_NODE_EXECUTOR_URI=x1-prover-v1tov2:50071
      - ZKEVM_NODE_MTCLIENT_URI=x1-prover-v1tov2:50061
      - ZKEVM_NODE_AGGREGATOR_UPGRADEETROGBATCHNUMBER=2
    volumes:
      - ./test/test.keystore.sequencer:/pk/keystore.sequencer
      - ./test/test.keystore.aggregator:/pk/keystore.aggregator
      - ./test/config/node/config.zkevm.node.toml:/app/config.toml
      - ./test/config/node/genesis.local-v1tov2.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"aggregator\""

  x1-mock-l1-network:
    container_name: x1-local-l1-network
    image: okexchain/x1-geth:e2e_v0.2.0_20240318
    ports:
      - 8545:8545

  x1-v1tov2-l1-network:
    container_name: x1-v1tov2-l1-network
    image: okexchain/x1-geth:e2e_v0.2.0_20240318
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  x1-prover:
    container_name: x1-prover
    image: hermeznetwork/zkevm-prover:v5.0.3
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # MockProver
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./test/config/prover/config.prover.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  x1-prover-v1tov2:
    container_name: x1-prover-v1tov2
    image: hermeznetwork/zkevm-prover:v5.0.3
    environment:
      - AGGREGATOR_CLIENT_HOST=x1-aggregator-v1tov2
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # MockProver
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./test/config/prover/config.prover.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  x1-bridge-service:
    container_name: x1-bridge-service
    image: x1-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=x1-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./sentinel/config.json:/app/sentinel_config.json
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-bridge run --cfg /app/config.toml"

  x1-bridge-service-v1tov2:
    container_name: x1-bridge-service-v1tov2
    image: x1-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=x1-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
      - ZKEVM_BRIDGE_ETHERMAN_L1URL=http://x1-v1tov2-l1-network:8545
      - ZKEVM_BRIDGE_ETHERMAN_L2URLS=http://x1-node-v1tov2:8123
      - ZKEVM_BRIDGE_NETWORKCONFIG_POLYGONZKEVMADDRESS=0x3Aa5ebB10DC797CAC828524e59A333d0A371443c
      - ZKEVM_BRIDGE_NETWORKCONFIG_POLYGONBRIDGEADDRESS=0x80a540502706aa690476D5534e26939894559c05
      - ZKEVM_BRIDGE_NETWORKCONFIG_L2POLYGONBRIDGEADDRESSES=0x80a540502706aa690476D5534e26939894559c05
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./sentinel/config.json:/app/sentinel_config.json
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/x1-bridge run --cfg /app/config.toml"