version: '3.5'
services:
  xgon-state-db:
    container_name: xgon-state-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./test/config/prover/initproverdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  xgon-pool-db:
    container_name: xgon-pool-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command: ["postgres", "-N", "500"]

  xgon-bridge-db:
    container_name: xgon-bridge-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  xgon-bridge-redis:
    container_name: xgon-bridge-redis
    image: redis
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_PORT=6379
      - REDIS_DATABASES=8

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181

  xgon-bridge-coin-kafka:
    image: wurstmeister/kafka
    container_name: xgon-bridge-coin-kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9123
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9123
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CREATE_TOPICS: "explorer_chainAddressPrice_push:1:1"

  xgon-node:
    container_name: xgon-node
    image: zjg555543/xgon-dac-node:v0.1.0
    ports:
      - 8123:8123
      - 61090:61090
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xgon-state-db
      - ZKEVM_NODE_POOL_HOST=xgon-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=xgon-rpc-db
      - ZKEVM_NODE_ETHERMAN_PRIVATEKEYPATH=/pk/keystore
    volumes:
      - ./test/test.keystore.sequencer:/pk/keystore.sequencer
      - ./test/test.keystore.aggregator:/pk/keystore.aggregator
      - ./test/config/node/test.node.config.toml:/app/config.toml
      - ./test/config/node/test.genesis.config.json:/app/genesis.json
    command: 
      - "/bin/sh"
      - "-c"
      - "/app/xgon-node approve --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml --key-store-path /pk/keystore.sequencer --password testonly &&
         /app/xgon-node run --genesis /app/genesis.json --cfg /app/config.toml --components \"synchronizer,rpc,sequencer,aggregator,eth-tx-manager,l2gaspricer\""

  xgon-mock-l1-network:
    container_name: xgon-local-l1-network
    image: zjg555543/geth-dac:v0.1.0
    ports:
      - 8545:8545
      - 8546:8546

  xgon-prover:
    container_name: xgon-prover
    image: hermeznetwork/zkevm-prover:v2.2.0
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # MockProver
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./test/config/prover/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  xgon-bridge-service:
    container_name: xgon-bridge-service
    image: xgon-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xgon-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
      - ./sentinel/config.json:/app/sentinel_config.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xgon-bridge run --cfg /app/config.toml"

  xgon-bridge-kafka-consumer:
    container_name: xgon-bridge-kafka-consumer
    image: xgon-bridge-service
    volumes:
      - ./config/config.local.toml:/app/config.toml
      - ./coinmiddleware/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xgon-bridge runKafkaConsumer --cfg /app/config.toml"

  xgon-data-availability:
    container_name: xgon-data-availability
    image: xgon-data-availability
    ports:
      - 8444:8444
    volumes:
      - ./config/node/test.da.toml:/app/config.toml
      - ./config/node/test-member.keystore:/pk/test-member.keystore
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xgon-data-availability run --cfg /app/config.toml"

  xgon-data-availability-db:
    container_name: xgon-data-availability-db
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"
