[Log]
Level = "debug"
Outputs = ["stdout"]

[Apollo]
Enabled = false
AppID = "x1-bridge-service"
Cluster = "default"
MetaAddress = "http://127.0.0.1:8080"
Namespaces = ["application"]
Secret = ""
IsBackupConfig = true

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "x1-bridge-db"
Port = "5432"
MaxConns = 20

[ClaimTxManager]
Enabled = true
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10
FreeGas = false
AuthorizedClaimMessageAddresses = ["0x90F79bf6EB2c4f870365E785982E1f101E93b906"]

[Etherman]
L1URL = "http://x1-mock-l1-network:8545"
L2URLs = ["http://x1-node:8123"]
L1ChainId = 5
L2ChainIds = [1001]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
SentinelConfigFilePath = "/app/sentinel_config.json"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "x1-bridge-db"
    Port = "5432"
    MaxConns = 20
    TableSuffix = ""
    [BridgeServer.Redis]
    IsClusterMode = false
    Addrs = ["x1-bridge-redis:6379"]
    Username = ""
    Password = ""
    DB = 0
    MockPrice = true

[CoinKafkaConsumer]
Brokers = ["x1-bridge-coin-kafka:9092"]
Topics = ["explorer_chainAddressPrice_push"]
ConsumerGroupID = "x1-bridge-service"
InitialOffset = -1
Username = ""
Password = ""
RootCAPath = "/app/root-ca-cert"

[MessagePushProducer]
Enabled = false

[NetworkConfig]
GenBlockNumber = 1
PolygonBridgeAddress = "0x1dDA31e2F009E7479dE78445C1540f55627a85f4"
PolygonZkEVMGlobalExitRootAddress = "0x6Ae5b0863dBF3477335c0102DBF432aFf04ceb22"
PolygonRollupManagerAddress = "0xF5336Cb12989c0673071dF0c8a930900D7DF8D3e"
PolygonZkEvmAddress = "0x975725832B4909Aab87D3604A0b501569dbBE7A9"
L2PolygonBridgeAddresses = ["0x1dDA31e2F009E7479dE78445C1540f55627a85f4"]

[NacosConfig]
NacosUrls = ""
NamespaceId = "public"
ApplicationName = ""
ExternalListenAddr = "127.0.0.1:26659"

[BusinessConfig]
StandardChainIds = [195]
InnerChainIds = [19500]
