[Log]
Level = "debug"
Outputs = ["stdout"]

[Apollo]
Enabled = false
AppID = "xlayer-bridge-service"
Cluster = "default"
MetaAddress = "http://127.0.0.1:8080"
Namespaces = ["application"]
Secret = ""
IsBackupConfig = true

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "xlayer-bridge-db"
Port = "5432"
MaxConns = 20
TableSuffix = ""

[ClaimTxManager]
Enabled = true
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10
FreeGas = false
AuthorizedClaimMessageAddresses = ["0x90F79bf6EB2c4f870365E785982E1f101E93b906"]

[Etherman]
L1URL = "http://xlayer-mock-l1-network:8545"
L2URLs = ["http://xlayer-json-rpc:8123"]
L1ChainId = 5
L2ChainIds = [1001]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
SentinelConfigFilePath = "/app/sentinel_config.json"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "xlayer-bridge-db"
    Port = "5432"
    MaxConns = 20
    TableSuffix = ""
    [BridgeServer.Redis]
    IsClusterMode = false
    Addrs = ["xlayer-bridge-redis:6379"]
    Username = ""
    Password = ""
    DB = 0
    MockPrice = true

[CoinKafkaConsumer]
Brokers = ["xlayer-bridge-coin-kafka:9092"]
Topics = ["explorer_chainAddressPrice_push"]
ConsumerGroupID = "xlayer-bridge-service"
InitialOffset = -1
Username = ""
Password = ""
RootCAPath = "/app/root-ca-cert"

[MessagePushProducer]
Enabled = false

[NetworkConfig]
GenBlockNumber = 1
PolygonBridgeAddress = "0x10B65c586f795aF3eCCEe594fE4E38E1F059F780"
PolygonZkEVMGlobalExitRootAddress = "0xEd236da21Ff62bC7B62608AdB818da49E8549fa7"
L2PolygonBridgeAddresses = ["0x10B65c586f795aF3eCCEe594fE4E38E1F059F780"]

[NacosConfig]
NacosUrls = ""
NamespaceId = "public"
ApplicationName = ""
ExternalListenAddr = "127.0.0.1:26659"
